import sys
import os


from transformer.models.transformer_legacy import *
from transformer.criterions.label_smoothed_cross_entropy import *
#from transformer.criterions.label_smoothed_cross_entropy2 import LabelSmoothedCrossEntropyCriterion as LabelSmoothedCrossEntropyCriterion2